import fs from 'node:fs';
import path from 'node:path';

type PrepareContext = {
	host_root: string;
	build_dir: string;
	index_path: string;
	modules: Record<string, { root: string }>;
};

const contextPath = requiredEnv('DYNAMIC_MODULES_PREPARE_CONTEXT');
const outputPath = requiredEnv('DYNAMIC_MODULES_PREPARE_OUTPUT');
const moduleId = process.env.DYNAMIC_MODULES_PREPARE_PLUGIN_MODULE || 'dynamic-tgui';
const pluginId = process.env.DYNAMIC_MODULES_PREPARE_PLUGIN_ID || 'dynamic-tgui-cli-wrapper';

const context = JSON.parse(fs.readFileSync(contextPath, 'utf8')) as PrepareContext;
const hostRoot = path.resolve(process.env.DYNAMIC_MODULES_HOST_ROOT || context.host_root);
const buildDir = path.resolve(
	process.env.DYNAMIC_MODULES_BUILD_DIR || path.join(hostRoot, context.build_dir),
);
const indexPath = path.resolve(
	process.env.DYNAMIC_MODULES_INDEX || path.join(hostRoot, context.index_path),
);
const moduleRootEntry = context.modules?.[moduleId]?.root;

if (!moduleRootEntry) {
	throw new Error(`prepare context does not include ${moduleId}`);
}

const moduleRoot = path.resolve(hostRoot, moduleRootEntry);
const cliPath = path.join(moduleRoot, 'tools', 'cli.ts');

if (!fs.existsSync(cliPath)) {
	throw new Error(`${moduleId}: missing tools/cli.ts`);
}

const wrapperPath = path.join(buildDir, 'tgui', 'cli.ts');
const wrapperImport = importSpecifier(path.dirname(wrapperPath), cliPath);

fs.mkdirSync(path.dirname(wrapperPath), { recursive: true });
fs.writeFileSync(
	wrapperPath,
	[
		'#!/usr/bin/env bun',
		'// Generated by Dynamic TGUI. Do not edit.',
		`process.env.DYNAMIC_MODULES_HOST_ROOT ??= ${JSON.stringify(hostRoot)};`,
		`process.env.DYNAMIC_MODULES_INDEX ??= ${JSON.stringify(indexPath)};`,
		`await import(${JSON.stringify(wrapperImport)});`,
		'',
	].join('\n'),
	'utf8',
);

writePrepareOutput({
	generated: {
		tgui_cli_file: relativeToHost(hostRoot, wrapperPath),
	},
	files: {
		'tgui/package.json': [
			{
				kind: 'prepare_plugin',
				module: moduleId,
				id: pluginId,
				output_file: relativeToHost(hostRoot, wrapperPath),
			},
		],
	},
});

function requiredEnv(name: string) {
	const value = process.env[name];
	if (!value) {
		throw new Error(`${name} is required`);
	}
	return value;
}

function importSpecifier(fromDir: string, target: string) {
	let relative = path.relative(fromDir, target).replace(/\\/g, '/');
	if (!relative.startsWith('.')) {
		relative = `./${relative}`;
	}
	return relative;
}

function relativeToHost(hostRoot: string, target: string) {
	return path.relative(hostRoot, target).replace(/\\/g, '/');
}

function writePrepareOutput(output: unknown) {
	fs.mkdirSync(path.dirname(outputPath), { recursive: true });
	fs.writeFileSync(outputPath, `${JSON.stringify(output, null, 2)}\n`, 'utf8');
}
