from __future__ import annotations

import json
import os
from pathlib import Path
from typing import Any


def main() -> None:
    context_path = Path(required_env("DYNAMIC_MODULES_PREPARE_CONTEXT"))
    output_path = Path(required_env("DYNAMIC_MODULES_PREPARE_OUTPUT"))
    host_root = Path(required_env("DYNAMIC_MODULES_HOST_ROOT")).resolve()
    build_dir = Path(required_env("DYNAMIC_MODULES_BUILD_DIR")).resolve()
    index_path = Path(required_env("DYNAMIC_MODULES_INDEX")).resolve()
    module_id = os.environ.get("DYNAMIC_MODULES_PREPARE_PLUGIN_MODULE", "dynamic-tgui")
    plugin_id = os.environ.get("DYNAMIC_MODULES_PREPARE_PLUGIN_ID", "dynamic-tgui-cli-wrapper")

    context = json.loads(context_path.read_text(encoding="utf-8"))
    module_root_entry = context.get("modules", {}).get(module_id, {}).get("root")
    if not module_root_entry:
        raise RuntimeError(f"prepare context does not include {module_id}")

    module_root = (host_root / module_root_entry).resolve()
    cli_path = module_root / "tools" / "cli.ts"
    if not cli_path.exists():
        raise RuntimeError(f"{module_id}: missing tools/cli.ts")

    wrapper_path = build_dir / "tgui" / "cli.ts"
    wrapper_import = import_specifier(wrapper_path.parent, cli_path)
    wrapper_path.parent.mkdir(parents=True, exist_ok=True)
    wrapper_path.write_text(
        "\n".join(
            [
                "#!/usr/bin/env bun",
                "// Generated by Dynamic TGUI. Do not edit.",
                f"process.env.DYNAMIC_MODULES_HOST_ROOT ??= {json.dumps(str(host_root))};",
                f"process.env.DYNAMIC_MODULES_INDEX ??= {json.dumps(str(index_path))};",
                f"await import({json.dumps(wrapper_import)});",
                "",
            ]
        ),
        encoding="utf-8",
        newline="\n",
    )

    write_json(
        output_path,
        {
            "generated": {
                "tgui_cli_file": relative_to_host(host_root, wrapper_path),
            },
            "files": {
                "tgui/package.json": [
                    {
                        "kind": "prepare_plugin",
                        "module": module_id,
                        "id": plugin_id,
                        "output_file": relative_to_host(host_root, wrapper_path),
                    }
                ]
            },
        },
    )


def required_env(name: str) -> str:
    value = os.environ.get(name)
    if not value:
        raise RuntimeError(f"{name} is required")
    return value


def import_specifier(from_dir: Path, target: Path) -> str:
    relative = os.path.relpath(target, from_dir).replace(os.sep, "/")
    if not relative.startswith("."):
        relative = f"./{relative}"
    return relative


def relative_to_host(host_root: Path, path: Path) -> str:
    return path.resolve().relative_to(host_root).as_posix()


def write_json(path: Path, data: Any) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")


if __name__ == "__main__":
    main()
